name: Data Collection

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC (customize this!)
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas

      - name: Run data scraper
        run: python src/scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api/ data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Data update $(date)"
            git push
          fi

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Data collection failed',
              body: `Data collection workflow failed on ${new Date().toISOString()}. Please check the logs: ${context.payload.repository.html_url}/actions/runs/${context.runId}`
            })
